name: LogixWelcome
version: '1.0'
main: com.sanamo.LogixWelcome.LogixWelcome
api-version: '1.21'
commands:
  welcomeconfig:
    description: Open the welcome settings GUI
    usage: /welcomeconfig
    permission: welcome.config
    permission-message: "&cYou do not have permission to use this command."
permissions:
  welcome.config:
    description: Allows access to the welcome configuration GUI
    default: op